@extends('layouts.workspace')
@section('title', 'Pratim cijene')
@section('content')
<div class="tool-heading"><div><div class="section-kicker">TVOJA LISTA / TVOJI USLOVI</div><h1>Dobar par.<br><em>Po tvojoj cijeni.</em></h1><p>Zadaj budžet ili prati povratak svog broja. Pri otvaranju ove stranice provjeravamo najnovije ponude zabilježene u katalogu.</p></div><a class="tool-button" href="{{route('catalog')}}">+ Pronađi model</a></div>
@unless(session('user_id'))<div class="guest-note"><span>Praćenja su sačuvana u ovoj sesiji. Prijavom ih poveži sa svojim profilom.</span><a class="tool-link" href="{{route('account')}}">Poveži račun ↗</a></div>@endunless
@if($lastCheck = \Illuminate\Support\Facades\Cache::get('alerts:last_checked'))<p class="field-help">Posljednja automatska provjera: {{\Carbon\Carbon::parse($lastCheck)->format('d.m.Y. H:i')}}. Provjere koriste posljednje uvezene ponude.</p>@endif
<div class="tool-stats"><div><strong>{{$alerts->where('is_active',true)->count()}}</strong><span>AKTIVNIH<br>PRAĆENJA</span></div><div><strong>{{$alerts->whereNotNull('triggered_at')->count()}}</strong><span>ISPUNJENIH<br>USLOVA</span></div><div><strong>{{$alerts->where('is_active',false)->whereNull('triggered_at')->count()}}</strong><span>UGAŠENIH<br>PRAĆENJA</span></div></div>
<div class="tool-columns"><div class="saved-list">
@forelse($alerts as $alert)
@php($current = $currentPrices[$alert->id])
<article class="saved-card"><div class="saved-card-head"><div><span class="mini-label">{{$alert->type==='price'?'PAD CIJENE':'POVRATAK VELIČINE'}} · {{$alert->size?'EU '.$alert->size:'SVE VELIČINE'}}</span><h3><a href="{{route('product.show',['slug'=>$alert->product->slug,'size'=>$alert->size])}}">{{$alert->product->name}}</a></h3></div><span class="status-pill {{$alert->triggered_at?'good':($alert->is_active?'':'muted')}}">{{$alert->triggered_at?'Uslov ispunjen ✓':($alert->is_active?'Pratimo ↘':'Ugašeno')}}</span></div>
<div class="price-comparison"><div><span>TRENUTNO U KATALOGU</span><strong>{{$current!==null?number_format($current,2,',','.'): 'Nedostupno'}} @if($current!==null)<small>KM</small>@endif</strong></div><div><span>{{$alert->type==='price'?'TVOJA CILJNA CIJENA':'TRAŽENA VELIČINA'}}</span><strong>{{$alert->type==='price'?number_format((float)$alert->target_price,2,',','.'):($alert->size?'EU '.$alert->size:'Bilo koja')}} @if($alert->type==='price')<small>KM</small>@endif</strong></div></div>
@if($alert->type==='price' && $current!==null)<div class="price-track" aria-hidden="true" style="--progress:{{min(100,max(0,(float)$alert->target_price/max(.01,$current)*100))}}%"><span></span></div><p class="price-caption">@if($current <= (float)$alert->target_price)Ponuda trenutno odgovara tvom budžetu. Provjeri je u trgovini.@elseJoš {{number_format($current-(float)$alert->target_price,2,',','.')}} KM do tvoje ciljne cijene.@endif</p>@elseif($alert->type==='restock')<p class="price-caption">{{$current!==null?'Tražena veličina je dostupna u katalogu.':'Još nema dostupne ponude koja odgovara tvom odabiru.'}}</p>@endif
@if($alert->triggered_at)<p class="field-help">Uslov zabilježen {{$alert->triggered_at->format('d.m.Y. H:i')}}. Cijena i dostupnost mogu se promijeniti.</p>@endif
<div class="saved-card-actions"><a class="tool-link" href="{{route('product.show',['slug'=>$alert->product->slug,'size'=>$alert->size])}}#ponude">Provjeri ponude ↗</a>@if($alert->is_active)<form method="post" action="{{route('alerts.destroy',$alert)}}">@csrf @method('DELETE')<button class="delete-button" type="submit">Ugasi praćenje</button></form>@else<form method="post" action="{{route('alerts.store',$alert->product)}}">@csrf<input type="hidden" name="type" value="{{$alert->type}}"><input type="hidden" name="size" value="{{$alert->size}}"><input type="hidden" name="target_price" value="{{$alert->target_price}}"><button class="delete-button" type="submit">Prati ponovo</button></form>@endif</div>
</article>
@empty
<div class="empty-tool"><span class="empty-symbol" aria-hidden="true">↘</span><h2>Koji par čekaš?</h2><p>Otvori željeni model i odaberi „Prati cijenu“. Upiši svoj budžet, a ovdje provjeri kada ponuda ispuni uslov.</p><a class="tool-button tool-button-blue" href="{{route('catalog')}}">Pronađi par za praćenje <b>↗</b></a></div>
@endforelse
</div><aside class="tool-panel panel-dark"><div class="section-kicker">PAMETNIJA KUPOVINA</div><h2>Ti biraš granicu.</h2><ol class="step-list"><li><strong>Odaberi model</strong><span>U katalogu otvori patike koje te zanimaju.</span></li><li><strong>Postavi svoje uslove</strong><span>Ciljna cijena, EU broj ili povratak veličine u ponudu.</span></li><li><strong>Provjeri ovdje</strong><span>Status se računa iz posljednjih podataka kataloga. Praćenja se prikazuju u aplikaciji; email i push poruke se ne šalju.</span></li></ol><a class="tool-button tool-button-acid" href="{{route('deals')}}">Vidi aktuelne akcije <b>↗</b></a></aside></div>
@endsection
