@extends('layouts.workspace')
@section('title','AErchi Shopping Agent')
@section('content')
<div class="tool-heading"><div><div class="section-kicker">AERCHI SHOPPING AGENT</div><h1>Tvoj sljedeći par.<br><em>Uz razloge za izbor.</em></h1><p>Opiši broj, budžet, boje i par koji već nosiš. Analiza koristi Fit DNA, stvarne ponude i historiju tvog broja.</p></div></div>
<form class="tool-form agent-form" method="post" action="{{route('agent.analyze')}}">@csrf
<div class="tool-field"><label for="agent-message">Šta tražiš?</label><textarea id="agent-message" name="message" maxlength="2000" required placeholder="Nosim Nike Air Max 270 broj 43 i taman mi je. Budžet 200 KM. Volim crne ili sive. Mogu čekati.">{{old('message',$message ?? '')}}</textarea></div>
<div class="inline-fields"><div class="tool-field"><label for="agent-size">EU broj (ako ga znaš)</label><input id="agent-size" name="size" value="{{old('size',request('size'))}}" maxlength="20"></div><div class="tool-field"><label for="agent-budget">Budžet u KM (opcionalno)</label><input id="agent-budget" name="budget" type="number" min="1" max="10000" step=".01" value="{{old('budget',request('budget'))}}"></div></div>
<button class="tool-button tool-button-blue">Analiziraj katalog ↗</button></form>
@isset($analysis)
<section class="tool-panel"><h2>Ovako smo razumjeli zahtjev</h2><p>Broj: {{$analysis['intent']['size'] ?? 'iz Fit DNA, gdje je moguće'}} · Budžet: {{$analysis['intent']['budget'] ? $analysis['intent']['budget'].' KM' : 'nije zadan'}} · Čekanje: {{$analysis['intent']['can_wait']?'prihvatljivo':'nije navedeno'}} · Brend: {{$analysis['intent']['brand'] ?? 'prema profilu ili svi'}}.</p><p>Boje: {{implode(', ',$analysis['intent']['colors']) ?: 'nisu zadane'}}. Povezanih zapisa iz opisa: {{count($analysis['intent']['anchors'])}}.</p>@foreach($analysis['intent']['warnings'] as $warning)<p>{{$warning}}</p>@endforeach<p class="field-help">Analiza prepoznaje navedene uslove pomoću pravila; nije opći chatbot. Namjenu, udobnost i medicinske potrebe ne procjenjuje iz naziva modela. Prikazujemo do šest izbora iz najviše 60 kandidata ({{$analysis['candidateCount']}} odgovara početnim filterima). Ispravi broj ili budžet iznad ako treba.</p></section>
<div class="agent-results">@forelse($analysis['results'] as $item)<article class="agent-result"><div class="section-kicker">{{$loop->iteration}} / EU {{$item['size']}}</div><h2><a href="{{route('product.show',['slug'=>$item['product']->slug,'size'=>$item['size']])}}">{{$item['product']->name}}</a></h2><strong>{{number_format($item['decision']['current'],2,',','.')}} KM · {{$item['decision']['title']}}</strong><p>{{$item['decision']['reason']}}</p><p>{{$item['fit']['reason'] ?? 'Broj je preuzet iz tvog zahtjeva; nemamo dodatne fit dokaze.'}}</p><small>Stock Pressure: {{$item['decision']['stock']['score'] !== null ? $item['decision']['stock']['score'].'/100' : 'nema dovoljno podataka'}} · Dostupno u {{$item['decision']['stock']['current_stores']}} provjerenih trgovina.</small><a class="tool-link" href="{{route('product.show',['slug'=>$item['product']->slug,'size'=>$item['size']])}}">Odluka, ponude i Watch ↗</a></article>@empty<div class="empty-tool"><h2>Nema dovoljno podataka za odgovarajući par.</h2><p>Navedi EU broj, dopuni Fit DNA ili proširi budžet/boje. Nećemo predložiti pogrešan broj samo da popunimo listu.</p><a href="{{route('fit-passport')}}">Dopuni Fit DNA</a></div>@endforelse</div>
@endisset
@endsection
