@extends('layouts.workspace')
@section('title', 'Skeniraj etiketu')
@section('content')
<div class="tool-heading"><div><div class="section-kicker">AERCHI LENS / PREPOZNAJ SVOJ PAR</div><h1>Mala etiketa.<br><em>Veliko otkriće.</em></h1><p>Pronađi šifru modela na etiketi, fotografiši je i potraži isti par u BiH katalogu. Ili jednostavno prepiši tekst.</p></div><span class="heading-tag">SKENIRAJ → PRONAĐI → UPOREDI</span></div>
<div class="tool-columns"><section class="tool-panel"><div class="section-kicker">01 / DODAJ ETIKETU</div><h2>Šta piše na tvom paru?</h2><form class="tool-form" method="post" action="{{route('scanner.scan')}}#scan-result" enctype="multipart/form-data" data-pending="Čitam etiketu…">@csrf<label class="upload-zone" for="image"><span aria-hidden="true">⌗</span><strong>Ubaci fotografiju etikete</strong><small>Odaberi fotografiju ili je prevuci ovdje.<br>JPG, PNG ili WebP · do 10 MB</small><input id="image" data-upload type="file" name="image" accept="image/jpeg,image/png,image/webp" required><img class="upload-preview" data-preview hidden alt="Pregled odabrane fotografije etikete"><small data-filename class="upload-filename" aria-live="polite"></small></label><button class="tool-button tool-button-blue" type="submit">Skeniraj i pronađi model <b>↗</b></button></form>
<details class="manual-entry" @if(old('label_text')) open @endif><summary>Nema fotografije? Unesi tekst s etikete.</summary><form class="tool-form" method="post" action="{{route('scanner.scan')}}#scan-result" data-pending="Tražim model…">@csrf<div class="tool-field"><label for="label-text">Brend, šifra modela i EU broj</label><textarea id="label-text" name="label_text" rows="3" maxlength="1000" required placeholder="NIKE DV1234-001 EU 43">{{old('label_text')}}</textarea><small class="field-help">Najprecizniji rezultat daje šifra modela (SKU / ART / Style). Nalazi se na etiketi ili kutiji.</small></div><button class="tool-button" type="submit">Pronađi po tekstu <b>↗</b></button></form></details>
</section><aside class="tool-panel panel-dark"><div class="section-kicker">ZA BOLJI REZULTAT</div><h2>Etiketa je ključ.</h2><ol class="step-list"><li><strong>Pogledaj ispod jezika</strong><span>Ili na naljepnici originalne kutije. Potrebni su nam slova i brojevi, ne fotografija cijele patike.</span></li><li><strong>Približi i osvijetli</strong><span>Šifra treba biti oštra i cijela u kadru. Izbjegni odsjaj i zgužvanu etiketu.</span></li><li><strong>Provjeri pročitano</strong><span>Prepoznavanje može pogriješiti. Ako je šifra netačna, ispravi je kroz ručni unos.</span></li></ol><a class="tool-button tool-button-acid" href="{{route('catalog')}}">Radije pretraži katalog <b>↗</b></a></aside></div>
@isset($result)<section class="tool-panel scan-result" id="scan-result"><div class="section-kicker">02 / REZULTAT PREPOZNAVANJA</div><h2>{{$result['matches']->isNotEmpty()?'Pronašli smo podudaranje.':'Još nismo pronašli isti model.'}}</h2><div class="scan-facts"><div><span>BREND</span><strong>{{$result['brand'] ?? 'Nije prepoznat'}}</strong></div><div><span>ŠIFRA MODELA</span><strong>{{$result['style_code'] ?? 'Nije prepoznata'}}</strong></div><div><span>EU VELIČINA</span><strong>{{$result['size'] ?? 'Nije prepoznata'}}</strong></div></div>
@foreach($result['matches'] as $match)<a class="scan-match" href="{{route('product.show',['slug'=>$match->slug,'size'=>$result['size']])}}"><div><strong>{{$match->name}}</strong><small>{{$match->brand}} · Otvori model i uporedi ponude</small></div><b>↗</b></a>@endforeach
@if($result['matches']->isEmpty())<p>Provjeri šifru i pokušaj ručni unos. Model možda još nije u katalogu. Možeš nastaviti pretragu po prepoznatom brendu i veličini.</p><a class="tool-button" href="{{route('catalog',array_filter(['brand'=>$result['brand'],'size'=>$result['size']]))}}#rezultati">Istraži slične modele <b>↗</b></a>@endif
<details class="manual-entry"><summary>Pročitani tekst etikete</summary><p class="scan-raw">{{$result['text']}}</p></details></section>@endisset
@endsection
