<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
 Schema::create('stores',function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->string('website_url');$t->boolean('is_active')->default(true);$t->timestamp('last_synced_at')->nullable();$t->timestamps();});
 Schema::create('products',function(Blueprint $t){$t->id();$t->string('brand')->index();$t->string('name');$t->string('model')->nullable()->index();$t->string('ean')->nullable()->index();$t->string('gtin')->nullable()->index();$t->string('mpn')->nullable()->index();$t->string('gender')->nullable()->index();$t->string('category')->nullable();$t->string('color')->nullable()->index();$t->string('slug')->unique();$t->timestamps();});
 Schema::create('offers',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->foreignId('store_id')->constrained()->cascadeOnDelete();$t->string('external_id');$t->string('external_sku')->nullable();$t->string('name_original');$t->decimal('price',10,2);$t->decimal('old_price',10,2)->nullable();$t->char('currency',3)->default('BAM');$t->string('availability')->default('unknown');$t->text('description')->nullable();$t->text('image_url')->nullable();$t->text('product_url');$t->timestamp('last_checked_at');$t->timestamps();$t->unique(['store_id','external_id']);});
 Schema::create('offer_variants',function(Blueprint $t){$t->id();$t->foreignId('offer_id')->constrained()->cascadeOnDelete();$t->string('size');$t->string('availability')->default('unknown');$t->decimal('price',10,2)->nullable();$t->timestamps();$t->unique(['offer_id','size']);});
 Schema::create('price_histories',function(Blueprint $t){$t->id();$t->foreignId('offer_id')->constrained()->cascadeOnDelete();$t->decimal('price',10,2);$t->timestamp('recorded_at');});
 Schema::create('product_matches',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->foreignId('offer_id')->constrained()->cascadeOnDelete();$t->decimal('confidence',4,3);$t->string('method');$t->enum('status',['confirmed','suggested','rejected'])->default('suggested');$t->timestamps();});
 Schema::create('import_runs',function(Blueprint $t){$t->id();$t->foreignId('store_id')->nullable()->constrained()->nullOnDelete();$t->timestamp('started_at');$t->timestamp('finished_at')->nullable();foreach(['products_found','products_created','offers_created','offers_updated','price_changes','failed_products'] as $c)$t->unsignedInteger($c)->default(0);$t->json('errors')->nullable();$t->timestamps();});
 } public function down():void {foreach(['import_runs','product_matches','price_histories','offer_variants','offers','products','stores'] as $x)Schema::dropIfExists($x);} };
